---
- - Bjelovarsko-bilogorska
  - BJ
- - Brodsko-posavska
  - SB
- - Dubrovačko-neretvanska
  - DU
- - Grad Zagreb
  - ZG
- - Istarska
  - IS
- - Karlovačka
  - KA
- - Koprivničko-križevačka
  - KC
- - Krapinsko-zagorska
  - KR
- - Ličko-senjska
  - GS
- - Međimurska
  - CA
- - Osječko-baranjska
  - OS
- - Požeško-slavonska
  - PZ
- - Primorsko-goranska
  - PG
- - Sisačko-moslavačka
  - SK
- - Splitsko-dalmatinska
  - ST
- - Šibensko-kninska
  - SI
- - Varaždinska
  - VZ
- - Virovitičko-podravska
  - VT
- - Vukovarsko-srijemska
  - VU
- - Zadarska
  - ZD
- - Zagrebačka
  - ZGZ
