# from http://en.wikipedia.org/wiki/ISO_3166-2:IN
---
- - Andhra Pradesh
  - AP
- - Arunachal Pradesh
  - AR
- - Assam
  - AS
- - Bihar
  - BR
- - Chhattisgarh
  - CT
- - Goa
  - GA
- - Gujarat
  - GJ
- - Haryana
  - HR
- - Himachal Pradesh
  - HP
- - Jammu and Kashmir
  - JK
- - Jharkhand
  - JH
- - Karnataka
  - KA
- - Kerala
  - KL
- - Madhya Pradesh
  - MP
- - Maharashtra
  - MH
- - Manipur
  - MN
- - Meghalaya
  - ML
- - Mizoram
  - MZ
- - Nagaland
  - NL
- - Orissa
  - OR
- - Punjab
  - PB
- - Rajasthan
  - RJ
- - Sikkim
  - SK
- - Tamil Nadu
  - TN
- - Tripura
  - TR
- - Uttarakhand
  - UL
- - Uttar Pradesh
  - UP
- - West Bengal
  - WB
- - Andaman and Nicobar Islands
  - AN
- - Chandigarh
  - CH
- - Dadra and Nagar Haveli
  - DN
- - Daman and Diu
  - DD
- - Delhi
  - DL
- - Lakshadweep
  - LD
- - Puducherry
  - PY

