---
- - Auckland
  - AUK
- - Bay of Plenty
  - BOP
- - Canterbury
  - CAN
- - "Hawke's Bay"
  - HKB
- - Manawatu-Wanganui
  - MWT
- - Northland
  - NTL
- - Otago
  - OTA
- - Southland
  - STL
- - Taranaki
  - TKI
- - Waikato
  - WKO
- - Wellington
  - WGN
- - West Coast
  - WTC
- - Gisborne District
  - GIS
- - Marlborough District
  - MBH
- - Nelson City
  - NSN
- - Tasman District
  - TAS
- - Chatham Islands Territory
  - CIT
