development:
  host: localhost
  database: bossa_in_rio_development

test:
  host: localhost
  database: bossa_in_rio_test

# set these environment variables on your prod server
production:
  uri: <%= ENV['MONGOLAB_URI'] %>
