main:
  pt-BR:
    O Bossa in Rio Hostel oferece todos os serviços que você possa querer.


    h4. Conforto e Segurança


    * Café da manhã com pães, geléias, manteiga, frutas, frios, queijos, cereal, leite, café e chá. Grátis.

    * Caipirinha de boas-vindas. Grátis.

    * Bar com música, mesa de sinuca, opções de cervejas e drinks.

    * Ar condicionado em todos quartos.

    * TV de LED. Canais internacionais. DVD com filmes e seriados. Grátis.

    * Lavanderia.

    * Sistema de segurança com câmeras.

    * Armário individual, Cofre e Luggage Storage. Grátis.

    * Roupa de cama, toalhas e travesseiros. Grátis.


    h4. Conectando com o mundo


    * Computadores com acesso a Internet e WiFi em todo o hostel.  Grátis e 24 horas!

    * Ligações telefônicas locais. Grátis.

    * Ligações interurbanas e internacionais. Serviços de impressão e fax.

    * Aceitamos cartões de crédito.


    h4. Indo, Vindo e Passeando


    * Translado desde ou para, aeroportos e rodoviária.

    * Serviços de taxi e de reserva de ônibus.

    * Informações sobre a cidade, mapas e dicas. Grátis.

    * Tours para os principais pontos turísticos da cidade.


    h4. Outros


    * Convites para shows, boates e partidas de futebol.

    * Aulas de violão de música brasileira.

    * Troca de livros.

    * Sem curfew/lockout
  en:
    The Bossa in Rio Hostel offers all the services you might want.


    h4. Confort and Safety


    * Breakfast with bread, jam, butter, fruits, cold cuts, cheese, cereal, milk, coffee and tea. Free.

    * Welcome Caipirinha. Free.

    * Bar with music, pool table and a choice of beers and drinks.

    * Air conditioning in all rooms.

    * LED TV. International channels. DVD movies and TV shows. Free.

    * Laundry.

    * Security system with CCTV.

    * Individual Cabinet, Luggage Storage and Safe. Free.

    * Bed linen, towels and pillows. Free.


    h4. Connecting with the world


    * Computers with Internet access and WiFi throughout the hostel. Free 24 hours!

    * Local phone calls. Free.

    * Connections and international calls. Printing and fax.

    * We accept credit cards.


    h4. Arriving, departing and sightseeing


    * Transfer to or from airports and bus station.

    * Taxi services and bus tickets reservation.

    * Information about the city, maps and tips. Free.

    * Tours to the main city sights.


    h4. Other


    * Tickets to concerts, nightclubs and football matches.

    * Guitar classes of Brazilian music.

    * Book exchange.

    * No curfew / lockoutmain
